language: ruby

git:
  depth: 1

services:
  - docker

script:
  - docker build -t $DOCKER_PRIVATE_REGISTRY/shell2http-ssh-runner .

deploy:
  provider: script
  script: bash travis-docker-push.sh || travis_terminate 1;
  on:
    branch: master
