version: '3'

services:
  shell2http:
    build: .
#    image: docker.korniychuk.pro/shell2http-ssh-runner
    ports:
      - 8000:8080
    environment:
      SSH_USERNAME: root
      SSH_SERVER: docker.korniychuk.pro
      RUNNER_MODE: urls-file-with-commands
      RUNNER_URLS_FILE: urls.cfg
#      RUNNER_MODE: command
#      REMOTE_COMMAND: cd ~ && ls -laH && docker-compose --version
#      REMOTE_SCRIPT_FILENAME: remote.sh
    volumes:
      - "~/.ssh/id_rsa:/code/ssh.key:ro"
      - "./test-urls.cfg:/code/urls.cfg"
#      - "./remote-custom.sh:/code/remote.sh"
