version: '3'

services:
  shell2http:
    build: .
#    image: docker.korniychuk.pro/shell2http-ssh-runner
    ports:
      - 8000:8080
    environment:
      SSH_USERNAME: root
      SSH_SERVER: docker.korniychuk.pro
#      REMOTE_SCRIPT_FILENAME: remote.sh
    volumes:
      - "/Users/anton/.ssh/id_rsa:/code/ssh.key:ro"
#      - "./remote-custom.sh:/code/remote.sh"
#      - "/var/run/docker.sock:/var/run/docker.sock:ro"
#      - ".:/deploy"
