version: '3'

services:
  shell2http:
    build: .
#    image: docker.korniychuk.pro/shell2http-ssh-runner
    ports:
      - 8000:8080
    environment:
      SSH_USERNAME: root
      SSH_SERVER: korniychuk.pro

      # URLs file with commands mode
      RUNNER_MODE: urls-file-with-commands
      RUNNER_URLS_FILE: urls.cfg

      # Command mode
#      RUNNER_MODE: command
#      REMOTE_COMMAND: cd ~ && ls -laH && docker-compose --version

      # Script file mode(default)
#      REMOTE_SCRIPT_FILENAME: remote.sh
    volumes:
      - "~/.ssh/id_rsa:/code/ssh.key:ro"

      # URLs file with commands mode
      - "./test-urls.cfg:/code/urls.cfg:ro"

      # Script file mode(default)
#      - "./remote-custom.sh:/code/remote.sh"
